name: 'CI'
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    # Job name
    name: Jest test
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        id: checkout
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm ci
      - name: Run Test
        run: npm test -- --coverage
      # This step prints an output (time) from the previous step's action.
      - name: Echo the testing's time
        run: echo 'The time was ${{ steps.checkout.outputs.time }}.'
      - name: Trigger Codecov
        run: bash <(curl -s https://codecov.io/bash)

